/** Console art credit: prints Jives' logo in DevTools, in the same spirit as the footer credit. */

interface LogoCell {
  color: string | null;
  text: string;
}

const logo: LogoCell[][] = [
  [
    { color: null, text: "    " },
    { color: "#e5fa57", text: "██" },
    { color: "#e4f955", text: "████" },
    { color: "#9faa3f", text: "██" },
    { color: "#261e17", text: "██" },
    { color: "#e3fa56", text: "██" },
    { color: "#e4f955", text: "████" },
    { color: "#2c281a", text: "██" },
    { color: "#e3f852", text: "██" },
    { color: "#e4f955", text: "██" },
    { color: "#cce04e", text: "██" },
    { color: "#8b9238", text: "██" },
    { color: "#e4f955", text: "████" },
    { color: "#767a31", text: "██" },
    { color: "#252018", text: "██" },
    { color: "#e4f956", text: "██" },
    { color: "#e4f955", text: "██████" },
    { color: "#d2e550", text: "██" },
    { color: "#251f17", text: "██" },
    { color: null, text: "  " },
    { color: "#e3fa56", text: "██" },
    { color: "#e4f955", text: "██████" },
    { color: "#4b4923", text: "██" },
    { color: "#2e1717", text: "██" },
  ],
  [
    { color: null, text: "    " },
    { color: "#231f16", text: "██" },
    { color: "#7c8233", text: "██" },
    { color: "#e4fa56", text: "██" },
    { color: "#a2ae40", text: "██" },
    { color: "#261e17", text: "██" },
    { color: "#252018", text: "██" },
    { color: "#daed52", text: "██" },
    { color: "#e4fa56", text: "██" },
    { color: "#2d2819", text: "██" },
    { color: "#e5f852", text: "██" },
    { color: "#d8ec52", text: "██" },
    { color: "#262017", text: "██" },
    { color: "#251f17", text: "██" },
    { color: "#e4fa55", text: "██" },
    { color: "#e4fa56", text: "██" },
    { color: "#777c33", text: "██" },
    { color: "#261e16", text: "██" },
    { color: "#e3fa55", text: "██" },
    { color: "#e4fa56", text: "██" },
    { color: "#272119", text: "██" },
    { color: "#4d4b25", text: "██" },
    { color: "#c6d84c", text: "██" },
    { color: "#262017", text: "██" },
    { color: "#e3fa55", text: "██" },
    { color: "#e4fa56", text: "██" },
    { color: "#919a3b", text: "██" },
    { color: "#252018", text: "██" },
    { color: "#262018", text: "██" },
    { color: "#dff454", text: "██" },
    { color: "#2f2b1a", text: "██" },
  ],
  [
    { color: null, text: "      " },
    { color: "#e3f856", text: "██" },
    { color: "#e4fa56", text: "██" },
    { color: "#a2ae40", text: "██" },
    { color: "#261e17", text: "██" },
    { color: null, text: "  " },
    { color: "#e3f956", text: "██" },
    { color: "#e4fa56", text: "██" },
    { color: "#2d2819", text: "██" },
    { color: "#e5f852", text: "██" },
    { color: "#d8ec52", text: "██" },
    { color: "#262017", text: "██" },
    { color: null, text: "  " },
    { color: "#e4fa55", text: "██" },
    { color: "#e4fa56", text: "██" },
    { color: "#777c33", text: "██" },
    { color: "#261e16", text: "██" },
    { color: "#e3fa55", text: "██" },
    { color: "#e4fa56", text: "██" },
    { color: "#272218", text: "██" },
    { color: "#292214", text: "██" },
    { color: "#252017", text: "██" },
    { color: "#261f17", text: "██" },
    { color: "#e3fa55", text: "██" },
    { color: "#e4fa56", text: "██" },
    { color: "#919a3b", text: "██" },
    { color: "#272016", text: "██" },
    { color: null, text: "  " },
    { color: "#e4fa55", text: "██" },
    { color: "#2f2b1a", text: "██" },
  ],
  [
    { color: null, text: "      " },
    { color: "#d1f151", text: "██" },
    { color: "#cdee50", text: "██" },
    { color: "#8c9d3b", text: "██" },
    { color: "#261e17", text: "██" },
    { color: null, text: "  " },
    { color: "#cfef51", text: "██" },
    { color: "#cdee50", text: "██" },
    { color: "#2c2819", text: "██" },
    { color: "#d1eb55", text: "██" },
    { color: "#bcda4a", text: "██" },
    { color: "#262017", text: "██" },
    { color: null, text: "  " },
    { color: "#d1f150", text: "██" },
    { color: "#cdee50", text: "██" },
    { color: "#6a732e", text: "██" },
    { color: "#261e16", text: "██" },
    { color: "#ceee51", text: "██" },
    { color: "#cdee50", text: "██" },
    { color: "#262117", text: "██" },
    { color: null, text: "      " },
    { color: "#cff051", text: "██" },
    { color: "#cdee50", text: "██" },
    { color: "#808d37", text: "██" },
    { color: "#272016", text: "██" },
    { color: null, text: "  " },
    { color: "#cef051", text: "██" },
    { color: "#2f2b1a", text: "██" },
  ],
  [
    { color: null, text: "      " },
    { color: "#a2da46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#769936", text: "██" },
    { color: "#261e17", text: "██" },
    { color: null, text: "  " },
    { color: "#a2da46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#2a2719", text: "██" },
    { color: "#9fd846", text: "██" },
    { color: "#9acf43", text: "██" },
    { color: "#262017", text: "██" },
    { color: null, text: "  " },
    { color: "#a1db46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#5a6e2b", text: "██" },
    { color: "#261e16", text: "██" },
    { color: "#a1da46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#262117", text: "██" },
    { color: null, text: "      " },
    { color: "#a2da45", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#6c8932", text: "██" },
    { color: "#272016", text: "██" },
    { color: null, text: "  " },
    { color: "#a2da46", text: "██" },
    { color: "#2b2919", text: "██" },
  ],
  [
    { color: null, text: "      " },
    { color: "#a2da46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#769936", text: "██" },
    { color: "#261e17", text: "██" },
    { color: null, text: "  " },
    { color: "#a2da46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#2a2719", text: "██" },
    { color: "#9fd846", text: "██" },
    { color: "#9acf43", text: "██" },
    { color: "#262017", text: "██" },
    { color: null, text: "  " },
    { color: "#a1db46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#5a6e2b", text: "██" },
    { color: "#261e16", text: "██" },
    { color: "#a1da46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#262117", text: "██" },
    { color: null, text: "      " },
    { color: "#a2da45", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#6c8932", text: "██" },
    { color: "#272016", text: "██" },
    { color: "#a3db47", text: "██" },
    { color: "#a1db47", text: "██" },
    { color: "#2b2919", text: "██" },
  ],
  [
    { color: null, text: "      " },
    { color: "#a2da46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#769936", text: "██" },
    { color: "#261e17", text: "██" },
    { color: null, text: "  " },
    { color: "#a2da46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#2a2719", text: "██" },
    { color: "#9fd846", text: "██" },
    { color: "#9acf43", text: "██" },
    { color: "#262017", text: "██" },
    { color: null, text: "  " },
    { color: "#a1db46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#5a6e2b", text: "██" },
    { color: "#261e16", text: "██" },
    { color: "#a1da46", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#262117", text: "██" },
    { color: null, text: "      " },
    { color: "#a2da45", text: "██" },
    { color: "#a2db47", text: "██" },
    { color: "#6c8932", text: "██" },
    { color: "#272016", text: "██" },
    { color: "#6d8a32", text: "██" },
    { color: "#739335", text: "██" },
    { color: "#282319", text: "██" },
  ],
  [
    { color: null, text: "      " },
    { color: "#6dbc3e", text: "██" },
    { color: "#62b63f", text: "██" },
    { color: "#4e7e30", text: "██" },
    { color: "#261e17", text: "██" },
    { color: null, text: "  " },
    { color: "#66b940", text: "██" },
    { color: "#62b63f", text: "██" },
    { color: "#282519", text: "██" },
    { color: "#72c243", text: "██" },
    { color: "#5db03d", text: "██" },
    { color: "#41772e", text: "██" },
    { color: "#3a6328", text: "██" },
    { color: "#59b23f", text: "██" },
    { color: "#62b63f", text: "██" },
    { color: "#425c27", text: "██" },
    { color: "#261e16", text: "██" },
    { color: "#67b740", text: "██" },
    { color: "#62b63f", text: "██" },
    { color: "#252117", text: "██" },
    { color: null, text: "      " },
    { color: "#6cbd44", text: "██" },
    { color: "#62b63f", text: "██" },
    { color: "#4b712e", text: "██" },
    { color: "#272016", text: "████" },
    { color: "#252019", text: "██" },
    { color: "#262116", text: "██" },
  ],
  [
    { color: "#52ac3d", text: "██" },
    { color: "#4ca03a", text: "██" },
    { color: "#262018", text: "██" },
    { color: "#52ac3d", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#427c30", text: "██" },
    { color: "#261e17", text: "██" },
    { color: null, text: "  " },
    { color: "#52ac3d", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#272418", text: "██" },
    { color: "#4eb03a", text: "██" },
    { color: "#52ac3d", text: "██" },
    { color: "#4c9e39", text: "██" },
    { color: "#3e6d2c", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#4a9436", text: "██" },
    { color: "#2b301c", text: "██" },
    { color: "#261e16", text: "██" },
    { color: "#52ac3e", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#4c9a38", text: "██" },
    { color: "#52ac3e", text: "██" },
    { color: null, text: "    " },
    { color: "#345525", text: "██" },
    { color: "#4b9939", text: "██" },
    { color: "#4fa73c", text: "██" },
    { color: "#4fa53b", text: "██" },
    { color: "#52ac3d", text: "██" },
    { color: "#2e3b1f", text: "██" },
    { color: null, text: "  " },
  ],
  [
    { color: "#51ab3e", text: "██" },
    { color: "#2e3a1f", text: "██" },
    { color: "#252018", text: "██" },
    { color: "#52ac3d", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#427c30", text: "██" },
    { color: "#261e17", text: "██" },
    { color: null, text: "  " },
    { color: "#52ac3d", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#272418", text: "██" },
    { color: null, text: "  " },
    { color: "#53ab3d", text: "██" },
    { color: "#51ac3d", text: "██" },
    { color: "#50aa3d", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#41742e", text: "██" },
    { color: "#262017", text: "██" },
    { color: "#272713", text: "██" },
    { color: "#52ac3e", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#314121", text: "██" },
    { color: "#314020", text: "██" },
    { color: null, text: "    " },
    { color: "#212116", text: "██" },
    { color: "#2c391e", text: "██" },
    { color: "#2f4220", text: "████" },
    { color: "#50a63c", text: "██" },
    { color: "#4fa93d", text: "██" },
    { color: "#282718", text: "██" },
  ],
  [
    { color: "#52ab3d", text: "██" },
    { color: "#262017", text: "██" },
    { color: "#281e14", text: "██" },
    { color: "#52ac3d", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#427c30", text: "██" },
    { color: "#261e17", text: "██" },
    { color: null, text: "  " },
    { color: "#52ac3d", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#272418", text: "██" },
    { color: null, text: "    " },
    { color: "#52ac3d", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#488c34", text: "██" },
    { color: "#29281b", text: "██" },
    { color: "#272118", text: "██" },
    { color: null, text: "  " },
    { color: "#52ac3e", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#262117", text: "██" },
    { color: "#3f7b33", text: "██" },
    { color: "#4d9d3a", text: "██" },
    { color: "#252017", text: "██" },
    { color: "#53ab3e", text: "██" },
    { color: "#4fa039", text: "██" },
    { color: "#251e16", text: "████" },
    { color: "#51aa3c", text: "██" },
    { color: "#52ad3e", text: "██" },
    { color: "#272719", text: "██" },
  ],
  [
    { color: "#2c331d", text: "██" },
    { color: "#51ab3d", text: "██████" },
    { color: "#468633", text: "██" },
    { color: "#272418", text: "██" },
    { color: "#261e17", text: "██" },
    { color: "#50aa3b", text: "██" },
    { color: "#51ac3d", text: "██" },
    { color: "#52ab3d", text: "██" },
    { color: "#262418", text: "██" },
    { color: null, text: "    " },
    { color: "#52a53a", text: "██" },
    { color: "#52ab3d", text: "██" },
    { color: "#427a30", text: "██" },
    { color: "#262018", text: "██" },
    { color: null, text: "    " },
    { color: "#51aa3d", text: "██" },
    { color: "#52ab3d", text: "██" },
    { color: "#51ab3e", text: "██" },
    { color: "#51ab3c", text: "██" },
    { color: "#4c9d39", text: "██" },
    { color: "#262017", text: "██" },
    { color: "#2c2a1b", text: "██" },
    { color: "#437e31", text: "██" },
    { color: "#51ab3d", text: "████" },
    { color: "#51ac3d", text: "██" },
    { color: "#314421", text: "██" },
    { color: "#262018", text: "██" },
  ],
  [
    { color: "#222211", text: "██" },
    { color: "#262018", text: "████████" },
    { color: "#252117", text: "██" },
    { color: null, text: "  " },
    { color: "#252018", text: "██" },
    { color: "#262018", text: "████" },
    { color: "#262017", text: "██" },
    { color: null, text: "    " },
    { color: "#271f17", text: "██" },
    { color: "#262018", text: "████" },
    { color: "#262116", text: "██" },
    { color: null, text: "    " },
    { color: "#261f18", text: "██" },
    { color: "#262018", text: "████████" },
    { color: "#252017", text: "██" },
    { color: null, text: "  " },
    { color: "#261f19", text: "██" },
    { color: "#262018", text: "████████" },
    { color: "#191919", text: "██" },
  ],
];

function printBrowserLogo(): void {
  let fmt = "";
  const styles: string[] = [];

  for (let i = 0; i < logo.length; i++) {
    for (const part of logo[i]) {
      fmt += `%c${part.text}`;
      styles.push(
        `color: ${part.color ?? "transparent"}; font-family: monospace; font-size: 10px; line-height: 6px;`,
      );
    }
    if (i < logo.length - 1) fmt += "\n";
  }

  // A separate console.log per row would let DevTools group/chunk them; one call keeps it a single block.
  console.log(fmt, ...styles);
}

printBrowserLogo();

console.info(
  "%c Site by Jives  %c jives.dev",
  "font-family: monospace; font-size: 11px; color: #595959;",
  "font-family: monospace; font-size: 11px; color: #ce8a2a;",
);
