#!/usr/bin/env bash
# Generates ambient-mode data locally (a real residential IP works far more
# reliably against YouTube than CI's runner IPs do) and pushes it as a
# GitHub release asset, which deploy.yml restores into .cache/data
# before its own build. Requires: yt-dlp, ffmpeg, gh (authenticated). Also
# runs unattended from launchd (see scripts/com.djzwackery.ambient-data-push.plist),
# whose PATH is minimal and doesn't include Homebrew or fnm's node shim.
set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
cd "$(dirname "$0")/.."
eval "$(fnm env)"
fnm use --install-if-missing --silent-if-unchanged

TAG=ambient-data-cache
TARBALL=ambient-data.tar.gz

# This directory doubles as an active dev checkout, so only pull when it's
# safe to: a dirty tree or a non-dev branch means real work might be in
# progress; skip the update rather than risk clobbering it.
if [ -n "$(git status --porcelain)" ]; then
  echo "[push-ambient-data] $(date): uncommitted changes present, skipping repo update."
elif [ "$(git branch --show-current)" != "dev" ]; then
  echo "[push-ambient-data] $(date): not on dev, skipping repo update."
else
  echo "[push-ambient-data] $(date): updating from origin/dev..."
  before=$(git rev-parse HEAD)
  git fetch origin dev
  git merge --ff-only origin/dev
  if [ "$(git rev-parse HEAD)" != "$before" ]; then
    npm install
  fi
fi

echo "[push-ambient-data] $(date): fetching latest videos and generating ambient data..."
npm run build

tar -czf "$TARBALL" -C .cache data

if gh release view "$TAG" >/dev/null 2>&1; then
  gh release upload "$TAG" "$TARBALL" --clobber
else
  gh release create "$TAG" "$TARBALL" \
    --title "Ambient data cache" \
    --notes "Auto-generated by scripts/push-ambient-data.sh. Not meant for humans. Holds ambient-mode video analysis, restored by deploy.yml." \
    --prerelease
fi

rm "$TARBALL"

gh workflow run deploy.yml
echo "Pushed ambient data and triggered a redeploy."
