name: Deploy Schedule
on:
  schedule:
    - cron: 00 01 * * 0-6
jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.19.0'

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install
        run: |
          npm install
          npm run-script build

      - name: Build and Deploy Repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: 'public'
          clean: true
          git-config-name: Chook
          git-config-email: Chooksta69@users.noreply.github.com
